Sparsification of Affine Equality Matrix
goblint/analyzer pull request #1625
Opened 2024-11-05 16:46 UTC by GollokG

This pull request contributes a sparse implementation of the Affine Equality Matrix.

This implementation is part of the assignment given by Tum practical WiSe 24/25 -  Automated Bug Hunting and Beyond (IN0012, IN2106, IN4301).

2025-01-14 14:57 UTC, GollokG commented
[SV-COMP24_unreach-call.recursified_nested_6.yml.log](https://github.com/user-attachments/files/18411799/SV-COMP24_unreach-call.recursified_nested_6.yml.log)

When testing on SV-Comp, the call given in the attached logfile produces a correct SV-Comp result, but goblint crashes with a stack overflow. We believe this happens during the witness phase. 
See stack trace below:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000749988b50085 in mpn_bc_get_str (str=0x643d35e8a2b3 "v;d", len=len@entry=0, up=0x643d35e91db0, un=1, base=base@entry=10) at mpn/get_str.c:174
174           MPN_COPY (rp + 1, up, un);
#0  0x0000749988b50085 in mpn_bc_get_str (str=0x643d35e8a2b3 "v;d", len=len@entry=0, up=0x643d35e91db0, un=1, base=base@entry=10) at mpn/get_str.c:174
#1  0x0000749988b5a722 in __gmpn_get_str (str=0x643d35e8a2b3 "v;d", base=10, up=0x643d35e91db0, un=1) at mpn/get_str.c:430
#2  0x0000643d1b6c6447 in ml_z_format ()
#3  0x0000643d1b49285a in camlGoblintCil__Cil__d_const_4277 () at z.ml:311
#4  0x0000643d1b4838b8 in camlGoblintCil__Cil__anon_fn_9145 () at src/cil.ml:3383
#5  0x0000643d1b476eb8 in camlGoblintCil__Pretty__anon_fn$5bpretty$2eml$3a761$2c21$2d$2d105$5d_2658 () at src/ocamlutil/pretty.ml:762
#6  0x0000643d1b26f641 in camlGoblint_std__GobPretty__sprint_23 () at src/util/std/gobPretty.ml:5
#7  0x0000643d1af23bce in camlGoblint_lib__Witness__anon_fn$5bwitness$2eml$3a252$2c18$2d$2d249$5d_1331 () at src/witness/witness.ml:221
#8  0x0000643d1b60ed70 in camlStdlib__List__iter_549 () at list.ml:110
#9  0x0000643d1af23875 in camlGoblint_lib__Witness__iter_node_957 () at src/witness/witness.ml:252
#10 0x0000643d1b60ed70 in camlStdlib__List__iter_549 () at list.ml:110
#11 0x0000643d1b60ed70 in camlStdlib__List__iter_549 () at list.ml:110
#12 0x0000643d1b60ed70 in camlStdlib__List__iter_549 () at list.ml:110
#13 0x0000643d1b60ed70 in camlStdlib__List__iter_549 () at list.ml:110
...
```

2025-01-17 13:36 UTC, DrMichaelPetter requested changes
Big review just in time for the weekend :-)

In general, I like a lot of what I have seen here. There are some things in general, though, mainly due to the transition from array to lists, sometimes leaving traces of algorithmic concepts of arrays in the code:

- check each instance, where some `.nth` calls have been performed in the context of some iteration. i.e. fold/recursive call, etc. If accesses are in sequence, then maybe simply directly iterating on the underlying list is a better idea then emulating random access with the penalty of linear runtime. This is not completely trivial to get rid of everywhere, since sometimes you may need to carry over iterator-like constructs or halfway-digested list stubs, but it may help
- `List.length` is not linear in ocaml, where array.length is

To better get an idea of where one should focus to optimize, it would be so helpful to post a diagram of where a large benchmark spends its time the most into the PR's github discussion stream; putting the Timing annotations back into actions for that would be a good start.

What I have a hard time with is determining whether the capsulation in sub-folders is a do or don't in goblint - maybe one of the more senior developers (@jerhard @michael-schwarz ) wants to give their feedback on this.

2025-01-17 13:36 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      in
Since m never changes throughout find_and_reduce, have you considered sorting m once as a preprocessing step, and then only ever sequentially extract each pivot?

2025-01-17 13:36 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +        in
Within the `List.fold_left`, we have with List.nth a linear time access - all while we iterate on the pivot_positions of m . Is that a concept from the array world, that does not necessarily make sense here? Would we not rather prefer to directly fold over all pivot rows?

2025-01-17 13:47 UTC, michael-schwarz commented on src/analyses/apron/affineEqualityAnalysis.apron.ml
> +open ListMatrix
Do these opens then not shadow each other? Especially the different flavors of `Vector` and `Matrix`?

2025-01-17 14:15 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        | (idx, value) :: xs, ((i, count) :: ys) when i < idx -> add_indices_helper vec ys (added_count + count) acc
```suggestion
        | (idx, _) :: _, ((i, count) :: ys) when i <= idx -> add_indices_helper vec ys (added_count + count) acc
```

2025-01-17 14:23 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayMatrix.ml
> +      | None -> None
What is this match supposed to achieve? It just returns the argument to match. Also why do both need to be copied? Does `rref_matrix_with` modify both arguments?

2025-01-17 14:30 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      "["^list_str t^"\n"
Why not use `Array.fold_left` and avoid going to a list?

2025-01-17 14:32 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +        Array.filteri (fun i x -> i < n) v (* TODO: take? *)
Is this not basically `BatArray.left`?

2025-01-17 14:34 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +        Array.set v n new_val
Does this not simply throw on its own without performing a check before?

2025-01-17 14:35 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +    let is_zero_vec v = not (Array.exists (fun x -> x <>: A.zero) v)
`for_all` does the same thing but is a bit more obvious.

2025-01-17 14:37 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +          compare_length_with v (i + 1) > 0 && x <>: A.zero) v) 1 = 0
What is this actually checking? It looks very complicated.

2025-01-17 14:37 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      Array.mapi f' (Array.combine v1 v2) (* TODO: iter2i? *)
I don't think the comment about `iter2i` makes sense here...

2025-01-17 14:43 UTC, michael-schwarz commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      in aux (length v - 1) []
Is this a `Array.fold_right` ?

2025-01-17 14:44 UTC, michael-schwarz commented on src/cdomains/affineEquality/matrix.ml
> +  val empty: unit -> t (* TODO: needs unit? *)
Well, does it?

2025-01-17 14:54 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ List.fold_lefti (fun acc i x -> if x <> A.zero then (i, x) :: acc else acc) [] l
Is this not basically a `List.filteri`?

------

https://github.com/ocaml/ocaml/blob/930d7e24241f9b48aa5e6f410a325ec1cd685a48/stdlib/list.ml#L269

In newer versions of OCaml this is marked as `tail-mod-cons` so even for huge lists, there's no need to make it tail-recursive manually, and I guess it becomes more readable like that. As Info2 people we appreciate the effort though!

2025-01-17 14:56 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ List.fold_lefti (fun acc i x -> if x <> A.zero then (i, x) :: acc else acc) [] l
`filteri_map` actually.

2025-01-17 15:00 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      "["^list_str t^"\n"
Should `show` not also be sparse here?

2025-01-17 15:03 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      | (idx, _)::[] when idx <> v.len -1 -> true
Do such entries occur? And what do they mean?

2025-01-17 17:36 UTC, feniup commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      failwith "Never implemented!"
Just checking in. The `SparseVector` functions are actually used in the `ListMatrix`.  As the `ListMatrix` Functor accepts `AbstractVector` and not specifically `SparseVector`, it was necessary to promote those functions into the `AbstractVector` interface. 

After we got told, that the analysis with affine relations is not used, because of the poor performance, we assumed the `ArrayMatrix`, `ArrayVector` respectively, will die after we improved the performance with our new implementation. Therefore we didn't bother to implement the functions here.

@DrMichaelPetter The question is, if the old implementation is really worth keeping.

2025-01-17 22:16 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      failwith "Never implemented!"
After some further inspection and your comment I realized, that there is probably one misconception; while we find it beneficial to swap out list matrices and array matrices, we see not so much benefit in mixing list matrix with array vector and vice versa. This level of interchangeability can maybe be removed.... A list matrix will probably always want to deal with list vectors.... Or is there some deeper reason why this should be done?

If list implementation keeps its advantage over arrays, it will midterm be the main affeq implementation - however, we still want to see how it fares over a few months, especially with next semester's adoption of subpolyhedra, an extension of affeq with intervals....

2025-01-18 10:16 UTC, DrMichaelPetter requested changes

2025-01-18 10:38 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      | (idx, _)::[] when idx <> v.len -1 -> true
The reason I am asking is because my understanding was that the last element of such a vector represents the constants, so these would represent relationships of the type $$c \cdot 1 = 0$$, which I am not sure one would describe as (according to the comment)

> an affine equality over only one variable, i.e., a constant

as either $$c = 0$$ and it holds vacuously, or $$c \neq 0$$ and we have $$\bot$$ for the entire thing?

But maybe I am missing something?

2025-01-18 11:02 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      | (idx, _)::[] when idx <> v.len -1 -> true
Exactly, but keep in mind, that the =0 part is just added in our interpretation of this representation, and what we have here are plain linear expressions, and c is a valid linear expression. 

During the run of the analysis, you sometimes happen you saturate your equation base and try to add another equation. Either it is subsumed by the others and is reduced to 0=0 by polynomial division, or you end up with a remainder c=0, which semantically signals bottom. 

Still, you need to perform polynomial division on the linear expressions and usually want to inspect the result.

2025-01-20 12:17 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      | (idx, _)::[] when idx <> v.len -1 -> true
Ok, we both completely misunderstood this part. We have clarified the purpose of this function by staring at the code for some time, and checking its calling context.

2025-01-20 12:21 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +       Constant vectors are represented by a two element list, however this is not an iff relationship.*)
```suggestion
    (**
       [is_const_vec v] returns true if the v can be interpreted as an expression with one variable and possibly a constant, i.e. x_i  + c
       *)
```

2025-01-21 14:27 UTC, CopperCableIsolator commented on src/analyses/apron/affineEqualityAnalysis.apron.ml
> +    let module AD_Array = AffineEqualityDomain.D2 (ArrayVector) (ArrayMatrix) in (* TODO: Remove this! Just to suppress warning *)
The ArrayMatrix is no longer opened anywhere, which prevents the warnings so this can be removed. The files remain however and should be removed as well.

2025-01-21 14:28 UTC, CopperCableIsolator commented on src/cdomains/affineEquality/abstractMatrix.ml
> +(** Some functions inside have the suffix _with, which means that the function has side effects. *)
Yes, the comment has been removed!

2025-01-21 15:19 UTC, CopperCableIsolator commented on src/cdomains/affineEquality/arrayImplementation/arrayVector.ml
> +      failwith "Never implemented!"
In the case of the list matrix, the "list" refers to the fact that we represent a matrix as a list of vectors, which themselves might not be sparse at all (or sparse in some other way, using hashmaps for example). I acknowledge that this is a bit weird, but the other possible option is to divide the two implementations in the Interface already. Another thing with this is would be that the Domain can currently not run the array implementation efficiently, since we removed side effects (which were basically bleeding). So should we split the two implementations, the most-sensical option (to us) would be to split at the domain level, which would leave us at two different Domains doing the same thing?!

2025-01-21 16:38 UTC, GollokG commented on src/cdomains/affineEquality/vector.ml
We provided descriptions for those functions in the sparseVector module now. They will be moved to the respective interface  later.

2025-01-22 11:31 UTC, charlotte-brandt commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ List.fold_lefti (fun acc i x -> if x <> A.zero then (i, x) :: acc else acc) [] l
Yes, thanks, we changed this.

2025-01-22 13:45 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      in {entries = entries'; len = List.length l}
Two comments: Please ident like so

~~~ocaml
    let ... = .... in
~~~

and not with the in in the next line. (I think it's like this almost everywhere).

Also, here field punning (https://dev.realworldocaml.org/records.html) makes to code a little nicer:

```suggestion
      let entries = List.filteri_map (fun i x -> if x <> A.zero then Some (i, x) else None) l in
      {entries; len = List.length l}
```

2025-01-22 13:48 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      {entries = entries'; len = len'}
field punning and get rid of the primed variables?

2025-01-22 13:54 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ Array.fold_lefti (fun acc i x -> if x <> A.zero then (i, x) :: acc else acc ) [] a in
In an array, this is a loop anyway and there's nor real need to prefer `fold_left` over `fold_right`. (See https://github.com/ocaml-batteries-team/batteries-included/blob/7d2c4f20b28f61450a129aeb886aa28ad5dd7ee7/src/batArray.ml#L98)

So a `BatArray.fold_righti` is the better choice here.

----

I know this isn't  what we preach in FPV, but OCaml is a bit bigger than the things we cover in class.

2025-01-22 14:06 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      in
```suggestion
      let rec extend_zero_aux i acc = function
          | (index, value) :: xs when index = i -> extend_zero_aux (i + 1) (value :: acc) xs
          | ((_:: _) as v) -> extend_zero_aux (i + 1) (A.zero :: acc) v
          | [] -> if i < v.len then extend_zero_aux (i + 1) (A.zero :: acc) [] else List.rev acc
      in
```

Not sure if this makes it easier to understand, but maybe yes? Please test before committing, not sure if it's 100% correct

2025-01-22 14:11 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        {entries = set_nth_helper v.entries []; len = v.len}
```suggestion
        {v with entries = set_nth_helper v.entries []}
```

2025-01-22 14:47 UTC, michael-schwarz reviewed
Some more minor remarks

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +       @raise Invalid_argument if [n] is out of bounds.
The comment should may mention that the other entries are shifted to the right.

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +            else (if num <>: A.zero then (idx + 1, value) :: (n, num) :: acc else (idx + 1, value) :: acc)
Is the element not added too often here? Naively, I would think one need not only check  if `num <> Zero` but also something about `n`?

Assume a full list `[(0,-5)),(1,-5),(2,-5)]` and I call `insert_val_at [(0,-5)),(1,-5),(2,3-5)] 1 42`, this would produce something like `[(0,-5)), (1,42), (2,-5), (1,42), (3,-5)]`, right? Am I missing something?

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        fst @@ List.findi (fun i (idx, value) -> if i < idx then true else f value) v.entries (* Here fst is the iteration variable i, not the tuple idx *)
```suggestion
        fst @@ List.findi (fun i (idx, value) ->  i < idx || f value) v.entries (* Here fst is the iteration variable i, not the tuple idx *)
```

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      in (exists_aux c f v.entries)
```suggestion
      let rec exists_aux at = function
        | [] -> if at = 0 then false (* vector is dense *) else f A.zero
        | (_, xv) :: xs -> f xv || exists_aux (at - 1) f xs
      in
      exists_aux c v.entries
```

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      {entries = entries'; len = v.len}
```suggestion
      {v with entries = entries'}
```

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      {entries = entries'; len = v.len}
Punning as above

2025-01-22 14:47 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ List.map (fun (idx, value) -> (v.len - 1 - idx, value)) v.entries in
`List.rev_map`?

2025-01-23 12:51 UTC, charlotte-brandt commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +            else (if num <>: A.zero then (idx + 1, value) :: (n, num) :: acc else (idx + 1, value) :: acc)
Yes, you're correct of course. We implemented this function to match the vector interface, however it is never called which is probably why we didn't notice this. We are currently considering whether we should keep (and fix) these uncalled functions or remove them.

2025-01-23 13:13 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +            else (if num <>: A.zero then (idx + 1, value) :: (n, num) :: acc else (idx + 1, value) :: acc)
If it's globally uncalled, I think we can just remove it.

2025-01-23 20:55 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +        in
Particularly after the inspection of the Timing results, this might be worth pursuing, since rref_vec is a hotspot.

2025-01-23 21:50 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
Ok, after staring the whole evening on the code and also taking a look at Karr's paper, I would drop this iterator idea of my last comment; however, theoretically switching to a (maybe even mutable) Hashtable temporarily during the computation of lin_discjunt would solve a lot of the performance penalties of this algorithm; the Hasthtables would basically still have a similar amount of entries as the sparse Lists, while allowing for row and column operations simultaneously... I mostly see only basic interactions with the matrices.... I must think a little bit about what one can do here.

2025-01-24 07:50 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
I now concentrated on Karr's paper solely. I think, this can be implemented without hashtables or random access, now. It is just not a little patch to the existing algorithm but a rather more involved change. Writing the idea down is kinda tedious and would probably cost similar effort as implementing it, but if you want to get the last bits of algorithmic tuning out of lin_discjunc, we can meet to talk about this idea.

2025-01-24 08:50 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +                sub_scaled_row acc piv_row v_at_piv
```suggestion
          | Some (pivot_col, _) -> (i, pivot_col,row) :: acc
      ) [] m

    (** 
       [reduce_col m j] reduces the [j]-th column in [m] with the last row that has a non-zero element in this column.
    *)
    let reduce_col m j = 
      if is_empty m then m 
      else
        let rec find_pivot idx entries = (* Finds non-zero element in column j and returns pair of row idx and the pivot value *)
          match entries with
          | [] -> None
          | row :: rest -> let value = V.nth row j in 
            if value =: A.zero then find_pivot (idx - 1) rest else Some (idx, value)
        in
        match (find_pivot (num_rows m - 1) (List.rev m)) with
        | None -> m (* column is already filled with zeroes *)
        | Some (row_idx, pivot) -> 
          let pivot_row = List.nth m row_idx in (* use the pivot row to reduce all entries in column j to zero, then "delete" the pivot row *)
          List.mapi (fun idx row ->
              if idx = row_idx then 
                V.zero_vec (num_cols m)
              else
                let row_value = V.nth row j in 
                if row_value = A.zero then row
                else (let s = row_value /: pivot in
                      sub_scaled_row row pivot_row s)            
            ) m

    (**
       [normalize m] transforms matrix [m] into reduced row echolon form (rref).
    *)
    let normalize m =
      let col_count = num_cols m in
      let cut_front_matrix m  row_idx col_idx = 
        List.filteri_map (fun i row -> if i < row_idx then None else Some (V.starting_from_nth row col_idx)) m
      in
      let cut_front_matrix m row_idx col_idx = Timing.wrap "cut_front_matrix" (cut_front_matrix m row_idx) col_idx in
      (* Function for finding first pivot in an extracted part of the matrix (row_idx and col_idx indicate which part of the original matrix) *)
      (* The last column represents the constant in the affeq *)
      let find_first_pivot m row_idx col_idx =
        if col_idx >= col_count then None else 
          let max_piv_col_idx = num_cols m - 2 in (* col at num_cols - 1 is the constant of the affeq *)
          (* Finding pivot by extracting the minimum column index of the first non zero value of each row *)
          let (piv_row, piv_col, piv_val) = List.fold_lefti (fun (cur_row, cur_col, cur_val) i row  -> 
              let row_first_non_zero = V.find_first_non_zero row in
              match row_first_non_zero with
              | None -> (cur_row, cur_col, cur_val)
              | Some (idx, value) -> if idx < cur_col then (i, idx, value) else (cur_row, cur_col, cur_val)
            ) (num_rows m, max_piv_col_idx + 1, A.zero) m 
          in
          if piv_col = (max_piv_col_idx + 1) then None else Some (row_idx + piv_row, col_idx + piv_col, piv_val)
      in
      let find_first_pivot m row_idx col_idx = Timing.wrap "find_first_pivot" (find_first_pivot m row_idx) col_idx in
      let affeq_rows_are_valid m = (* Check if the semantics of an rref-affeq matrix are correct *)
        let col_count = num_cols m in
        let row_is_valid row =
          match V.find_first_non_zero row with
          | Some (idx, _) -> if idx < col_count - 1 then true else false (* If all cofactors of the affeq are zero, but the constant is non-zero, the row is invalid *)
          | None -> true 
        in
        List.for_all row_is_valid m in
      (* Finds the best fitting pivot, moves the respective row at the correct position, and reduces the pivot column afterwards. Continues with next row after that until fully normalized *)
      let rec find_piv_and_reduce m m' row_idx col_idx = 
        if col_idx >= (col_count - 1) then m  (* In this case the whole bottom of the matrix starting from row_index has been reduced to Zero, so it is normalized *)
        else
          match find_first_pivot m' row_idx col_idx with
          | None -> m (* No pivot found means already normalized *)
          | Some (piv_row_idx, piv_col_idx, piv_val) -> (
              let m = if piv_row_idx <> row_idx then swap_rows m row_idx piv_row_idx else m in
              let normalized_m = List.mapi (fun idx row -> if idx = row_idx then div_row row piv_val else row) m in
              let piv_row = (List.nth normalized_m row_idx) in
              let subtracted_m = List.mapi (fun idx row -> if idx <> row_idx then 
                                               let scale = V.nth row piv_col_idx in
                                               sub_scaled_row row piv_row scale else row) normalized_m in
              let m' = cut_front_matrix subtracted_m (row_idx + 1) (piv_col_idx + 1) in
              find_piv_and_reduce subtracted_m m' (row_idx + 1) (piv_col_idx + 1)) (* We start at piv_col_idx + 1 because every other col before that is zero at the bottom*)
      in 
      let m' = find_piv_and_reduce m m 0 0 in
      if affeq_rows_are_valid m' then Some m' else None


    let normalize m = Timing.wrap "normalize" normalize m

    (** 
       [reduce_col_with_vec m j v] sets the [j]-th column of [m] to zero by subtracting multiples of [v] from each row. *)
    let reduce_col_with_vec m j v = 
      let pivot_element = V.nth v j in
      if pivot_element = A.zero then m
      else List.mapi (fun idx row ->
          let row_value = V.nth row j in 
          if row_value =: A.zero then row
          else (let s = row_value /: pivot_element in
                V.map2_f_preserves_zero (fun x y -> x -: (s *: y)) row v)
        ) m

    (** 
       [insert_v_according_to_piv m v piv_idx pivot_position] inserts vector [v] into [m] such that rref is preserved.
        @param m A matrix in rref such that [(r, piv_idx)] is not in [pivot_positions] for all [r]. 
        @param v A vector such that [v(piv_idx) =: A.one] and [v(c) <>: A.zero] if [(r,c)] is not in [pivot_position] for all [r]. 
    *)
    let insert_v_according_to_piv m v piv_idx pivot_positions = 
      let reduced_m = reduce_col_with_vec m piv_idx v in
      match List.find_opt (fun (row_idx, piv_col) -> piv_col > piv_idx) pivot_positions with
      | None -> append_row reduced_m v
      | Some (row_idx, _) -> 
        let (before, after) = List.split_at row_idx reduced_m in 
        before @ (v :: after)

    (** 
       [rref_vec m v] yields the same result as appending [v] to [m], then bringing [m] into rref and removing all zero rows.

       {i Faster than appending [v] to [m] and normalizing!}
       @param m A matrix in rref.
       @param v A vector with number of entries equal to the number of columns of [v].
    *)
    let rref_vec m v =
      if is_empty m then (* In this case, v is normalized and returned *)
        BatOption.map (fun (_, value) -> init_with_vec @@ div_row v value) (V.find_first_non_zero v)
      else (* We try to normalize v and check if a contradiction arises. If not, we insert v at the appropriate place in m (depending on the pivot) *)
        let pivot_positions = get_pivot_positions m in
        let v_after_elim = List.fold_left (
            fun acc (row_idx, pivot_position, piv_row) ->
              let v_at_piv = V.nth acc pivot_position in 
              if v_at_piv =: A.zero then 
                acc
              else
                sub_scaled_row acc piv_row v_at_piv
```
This should make one List.nth nested in a fold_left unneccessary

2025-01-24 09:03 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +              if v_at_piv =: A.zero then
I wonder, whether you can get reduce the impact of this V.nth by filtering pivot_positions by positions that have been 0 in the original v as a preprocessing step outside of the fold.

2025-01-24 09:34 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +                sub_scaled_row acc piv_row v_at_piv
Thank you, we included that into the `get_pivot_positions` function!

2025-01-24 12:34 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      List.mapi (fun index row -> if index < vector_length then f row (V.nth v index) else row ) m
```ocaml
let chopchop v =
  { entries = tl v.entries; len = v.len }
let map2_newandimproved f m v =
  let vector_length = V.length v in
  let result = List.fold_lefti (fun (res,vtail) index row -> 
    if index < vector_length then 
      let vval,vtail = match (V.find_first_non_zero vtail) with
      | Some (i,vval) when i = index -> vval, V.chopchop vtail
      | _ -> A.zero,vtail in
      f row vval ::res, vtail 
    else 
      row ::res,vtail ) ([],v) m in
  fst result
```
Is something like this a bad idea?

2025-01-24 13:32 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
>            | x -> x
Are we expecting to violate the vector length on purpose?

2025-01-24 13:32 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +                Matrix.map2i (fun i' x c -> if i' <= max then (let beta = c /: diff in Vector.map2_f_preserves_zero (fun u j -> u -: (beta *: j)) x t) else x) m col_a;
```suggestion
                Matrix.map2i (fun i' x c -> if i' <= max then (let beta = c /: diff in Vector.map2_f_preserves_zero (fun u j -> u -: (beta *: j)) x t) else x) m col_a
```
This looks like a fragment of the earlier transformation from side-effected arrays to immutable lists. We have seen that elsewhere as well, but keeping such a semicolon here is just asking for weirdly unexplicable errors.

2025-01-24 13:32 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
https://github.com/CopperCableIsolator/goblint-sparsification/blob/426d739cf7c9e96cfc74afed8917debfb71bd0e2/src/cdomains/apron/affineEqualityDomain.apron.ml#L323

please replace:
 ```ocaml
          begin match Int.of_float @@ Mpqf.to_float @@ a_rs, Int.of_float @@ Mpqf.to_float @@ b_rs with (* TODO: is it safe to go through floats? *)
```
with
```ocaml
          begin match Z.to_int @@ Mpqf.get_num a_rs, Z.to_int @@ Mpqf.get_num b_rs with
```

2025-01-24 14:22 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      {entries = ls; len = count}
This function is used in ListMatrix.get_col for example where the column vector is built from a sparse list. In cases like this it can be useful when a vector is to be constructed, but one wants to prevent a temporary blow up of the list's length because of Zero entries (it shrinks to its sparse representation for the SparseVector again).
Thanks for the hint, we added an explanation of the invariants in the function description.

2025-01-24 14:27 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +      let entries' = List.rev @@ Array.fold_lefti (fun acc i x -> if x <> A.zero then (i, x) :: acc else acc ) [] a in
Thanks for pointing that out, we changed it to fold_righti

2025-01-25 17:18 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      in
List.length would have to be used inside the List.map again, right? Isn't that something we wanted to avoid?

2025-01-25 19:18 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        in nth v.entries
An alternative would be:

```ocaml
let nth v n = (* Note: This exception HAS TO BE THROWN! It is expected by the domain *)
   if n >= v.len then raise (Invalid_argument "Index out of bounds")
   else
      match List.find_opt (fun (idx, _) -> idx >= n) v.entries with
      | Some (idx, value) when idx = n -> value
      | _ -> A.zero
```

But testing it showed that the current version is more efficient in runtime as well as memory. Because of the heavy use of this function, I think we should stick to the current? Or do you see another alternative?

2025-01-25 19:36 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        in nth v.entries
It reads so much better, though.... How much do we have to pay for this in terms of runtime% or rather memory%?

2025-01-25 20:02 UTC, michael-schwarz commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        in nth v.entries
~~~Ocaml
try
   List.find (fun (idx,_) -> if idx = n then true else if idx > n then raise Not_found (* early abort *) else false) v.entries
with Not_found ->
   A.zero
~~~

How does this one performance wise? And what do y'all think about it?

2025-01-25 20:55 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
Given, that you could change the `get_col..
.` function to return not only the column, but also the last (idx,val) that is not zero, I think that you could get rid of a lot of calls to `nth` as well as `rev`. Especially in case_three.

2025-01-25 22:03 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
The more I think about case three, the more I am convinced, that you do not even necessarily have to choose the column element with the largest row index - you might as well choose the one with the smallest index. That would be easy to change, and make case three considerably more easy to implement efficiently.

2025-01-26 10:09 UTC, sim642 commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        in nth v.entries
I probably don't have all of the context here, but such (short-circuiting) key search on a sorted list suggests something different to me: a `Map`.

2025-01-26 10:16 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +                Matrix.map2i (fun i' x c -> if i' <= max then (let beta = c /: diff in Vector.map2_f_preserves_zero (fun u j -> u -: (beta *: j)) x t) else x) m col_a
It is probably safe to check for `i' <= max` here, but is Karr not talking about `multiply_by_t` being applied to only rows strictly smaller then the rowindex `Vector.length col_a - i` ? In case, that there are equal non-zero entries in a and b, might that not even mess up rref if we apply m`multiply_by_t` to all rows?

2025-01-26 11:04 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +              if v_at_piv =: A.zero then
We tried that on our fork branch [`rref_vec_optimization`](https://github.com/CopperCableIsolator/goblint-sparsification/tree/rref_vec_optimizationl). It seems to be faster at least in bigger examples (maybe we can verify that with another SV-Comp run). The bottleneck now is the `insert_v_according_to_piv` function. At the current `master`  we use the pivot positions to determine the row idx where v can be inserted. With the optimized version, some pivot positions have to be extracted again in `insert_v_according_to_piv`.
For example if we have the matrix `m`
`[0, 1, 0, 1]`
and vector `v`
`[1, 0, 0, 1]`
the current `master` insert logic would append `v` to the `m` instead of making it the first row because the pivot list is empty (there was no pivot column in `m` with a corresponding non-zero entry in `v`.

2025-01-27 08:06 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +              if v_at_piv =: A.zero then
Ah, I see - you directly changed `get_pivot_positions` to do the filtering directly. 

In my idea, I would have thought, that you would do the filtering in a postprocessing step after `get_pivot_positions` is done, and use the filtered result only for the `fold_left` ... Sure, for the `insert_v_according_to_piv` you will need the full blown `pivot_positions`.

2025-01-27 09:41 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
>            let col_a, col_b = Vector.keep_vals col_a max, Vector.keep_vals col_b max in
Does `keep_vals` make any sense here? In this context here we only ever enter `case_three` only if there are no pivot elements anyway, as established by the match. Why do we then need to filter?

2025-01-27 10:10 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +              let col_a = Vector.map2_f_preserves_zero (-:) col_a col_b in
Is there a particular reason for doing the subtraction on the reversed columns and then reversing the result?

2025-01-27 10:23 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
>            if Vector.equal col_a col_b then
Considering, that a few lines later, we do a subtraction of col_a and col_b, we may do the subtraction already here, and check for an empty vector to decide equality. The difference vector can be used later on (line 308), instead of recomputing.

2025-01-28 07:49 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +              if v_at_piv =: A.zero then
Sorry, I had to check what drop_while does (quite useful indeed), so I did not recognize the algorithm immediately. But yes, this looks like what I would have imagined. Does it work?

2025-01-28 15:11 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +              if v_at_piv =: A.zero then
It seems to work and does have some positive performance impact. Maybe we can benchmark it in SV-Comp

2025-01-28 16:04 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      Timing.wrap "get_col" (get_col m) n
We deleted the function

2025-01-28 16:04 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +        List.map (fun row -> V.remove_nth row j) m
We deleted this function

2025-01-28 16:23 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      in
To be able to sort m, we would have to know what the col_idx of the respective pivots are. But those positions are only revealed after reducing the columns having a lower index.
Maybe I don't understand your idea, can you please elaborate on that?

2025-01-28 16:48 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        in nth v.entries
We chose the List.find_opt option since the performance overhead is not as big as expected. One could think of later changing the vector type t to something like a Map, but in this implementation we use the sparse list representation everywhere.

2025-01-28 16:50 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +        fst @@ List.findi (fun i (idx, value) -> if i < idx then true else f value) v.entries (* Here fst is the iteration variable i, not the tuple idx *)
This function was deleted, but still thanks for the hint

2025-01-30 13:51 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +    let num_rows = List.length
We've tried storing the number of rows in a record type for each matrix (see [this commit](https://github.com/CopperCableIsolator/goblint-sparsification/commit/fa86c02bf7f9a7670cac6049e1d8af4bc6ce831e) on our `cached-length` branch). In that form, it did not have significant impact locally. Maybe this idea can be picked up in the future?

2025-01-30 14:06 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      List.mapi (fun index row -> if index < vector_length then f index row (V.nth v index) else row ) m
We've tried the map2 and map2i implementations in [this commit](https://github.com/CopperCableIsolator/goblint-sparsification/commit/5e169850b6967623961e267913a645640e2798e6). Locally it did not have significant impact on performance.

Besides from that, we tried the following:

```ocaml
let map2_newandimproved f m v =
      let vector_length = V.length v in
      let result = List.fold_lefti (fun (res,vtail) index row ->
        if index < vector_length then
          let vval,vtail = match vtail with
          | (i,vval)::vtail when i = index -> vval, vtail
          | _ -> A.zero,vtail in
          (f row vval)::res, vtail
        else
          (row :: res),vtail ) ([],V.to_sparse_list v) m in
      List.rev @@ fst result
```
Also with no satisfying result.
Should we stick to the current simple (and readable) implementation, one of the other two versions which skip already processed entries of v (which sounds like it should be faster)?

2025-01-30 14:36 UTC, GollokG commented on src/cdomains/apron/affineEqualityDomain.apron.ml
>            if Vector.equal col_a col_b then
Thanks for the hint, we changed that!

2025-01-30 14:36 UTC, GollokG commented on src/cdomains/apron/affineEqualityDomain.apron.ml
>            if Vector.equal col_a col_b then
Thanks for the hint, we changed that!

2025-01-30 14:56 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      List.mapi (fun index row -> if index < vector_length then f index row (V.nth v index) else row ) m
I would like to see one of the versions that get rid of the `.nth` call, simply since their performance gains might just currently overshadowed by other opportunities that we have not optimized yet - it really looks more efficient.

2025-01-30 14:57 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +    let num_rows = List.length
Maybe it is not worth to cache the length, as long as we are not excessively call `.length` as if came for free.

2025-01-30 15:56 UTC, GollokG commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +              let col_a = Vector.map2_f_preserves_zero (-:) col_a col_b in
We changed it to subtract the original cols before reversing

2025-01-31 08:39 UTC, DrMichaelPetter commented on src/cdomains/affineEquality/sparseImplementation/listMatrix.ml
> +      in
Never mind, I think it is fine as it is.

2025-02-03 09:26 UTC, jerhard commented
Thanks for the PR. @GollokG  To document this PR better for people  who may look at it in the future , could you please add a few sentences in your top post to elaborate on your approach and what you have changed?

2025-02-11 12:51 UTC, DrMichaelPetter approved these changes

2025-02-13 09:10 UTC, sim642 commented on src/cdomains/affineEquality/vector.ml
> +end
Why is this in `vector.ml` if there's also `sparseVector.ml` for which this seems to be the interface?
Or even further, why isn't this just in `sparseVector.mli`?

(Same with `ArrayVector` interface above.)

2025-02-13 09:10 UTC, sim642 commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +module Array = BatArray
This is excessive. If you `open Batteries`, then `List` already is `BatList`, etc.
Also it's opening `BatList` itself, which is a bit too much I think. The code below seems to explicitly use `List.length`, etc not `length`.

Same in a lot of other modules it seems.

2025-02-13 09:10 UTC, sim642 commented on src/cdomains/affineEquality/ratOps.ml
> +    One could later exchange "Mpqf" with a different module that provides the functions specified by this interface. *)
Does this mean that all the dense/sparse vector/matrix implementations are truly independent from Apron?

2025-02-13 09:10 UTC, sim642 commented on src/cdomains/affineEquality/convenienceOps.ml
> +module ConvenienceOps (A: RatOps) =
This could just be in `ratOps.ml` to not pollute the top-level module namespace.

2025-02-13 09:10 UTC, sim642 commented on src/analyses/apron/affineEqualityAnalysis.apron.ml
> +   open ArrayMatrix *)
This is very hard-coded and manual. It should be easy to just make an option for this (if not register two separate analyses with separate names, but that might be too much).

2025-02-15 13:38 UTC, GollokG commented on src/cdomains/affineEquality/sparseImplementation/sparseVector.ml
> +module Array = BatArray
Thanks for the hint, we will change that, so that we only open Batteries in such cases.
We are going to address this and your other suggestions sometime next week.

2025-02-18 16:48 UTC, charlotte-brandt commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +let () = run_test_tt_main tests
You're right, I changed this so they should only be executed once now.

2025-02-18 16:51 UTC, charlotte-brandt commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +let () = run_test_tt_main tests
I just saw that this was already done a few days ago. Regardless they only run once now.

2025-02-18 18:34 UTC, charlotte-brandt commented on src/cdomains/affineEquality/vector.ml
> +end
We had issues creating `.mli` files because of the functors that replace `num` with `RatOps` which were in the original implementation. We thought it would be nice to have all the vector interfaces in one place but if you think it is better for each file to include its interface we can also move `module type SparseVector` and `SparseVectorFunctor` to `sparseVector.ml` (and the same for the other interfaces).

2025-02-19 09:42 UTC, GollokG commented on src/cdomains/affineEquality/ratOps.ml
> +    One could later exchange "Mpqf" with a different module that provides the functions specified by this interface. *)
In functions like `add_empty_columns` we expect an array telling us in where to change the dimensions. This array is expected to have Apron's `change.dim` semantics, so it stores the indices for the new columns.
But apart from that, the matrix and vector implementations are independent from Apron because of abstractions like `RatOps`.

2025-02-20 08:51 UTC, charlotte-brandt commented on src/cdomains/affineEquality/vector.ml
> +end
Okay, I changed this. The interfaces as well as the functors are now in their respective files.

2025-02-21 15:00 UTC, GollokG commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
We added a .no-apron test file. It currently doesn't test anything because there currently is no RatOps implementation other than Mpqf, but now it does compile without Apron.

2025-02-21 15:15 UTC, GollokG commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
However, we ran into an issue with cyclic dependencies when specifying the alternative dependencies for dune, so the tests are located `tests/unit` but not deeper in the hierarchy.
We tried adding
`(copy_files# cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.*.ml)
`
to the testing dune file as suggested in [this issue](https://github.com/ocaml/dune/issues/4383#issuecomment-805107435), but got the error

```
Error: Dependency cycle between:  
   Computing directory contents of _build/default/tests/unit
-> { dir =
       In_build_dir
        
   "default/tests/unit/cdomains/affineEqualityDomain/sparseImplementation"
   ; predicate = Glob (Glob "sparseMatrixImplementationTest.*.ml")
   ; only_generated_files = false
   }
-> Computing directory contents of _build/default/tests/unit
```

2025-02-22 08:51 UTC, GollokG commented on src/analyses/apron/affineEqualityAnalysis.apron.ml
> +   open ArrayMatrix *)
We have now added the  `--enable ana.affeq.side_effects` option to change to the side effect version

2025-02-22 09:55 UTC, GollokG commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
All "unlocked" jobs work now on our branch, except for [lower-bounds](https://github.com/CopperCableIsolator/goblint-sparsification/actions/runs/13468741316/job/37639363284) revealing this issue:

```
Warning:  OPAMCONFIRMLEVEL was ignored because CLI 2.0 was requested and it was introduced in 2.1.
File "/home/runner/work/goblint-sparsification/goblint-sparsification/_opam/lib/ocaml-compiler-libs/bytecomp/ocaml-compiler-libs.bytecomp.dune", line 1, characters 0-0:
Warning: .dune files are ignored since 2.0. Reinstall the library with dune
>= 2.0 to get rid of this warning and enable support for the subsystem this library provides.

...

File "tests/unit/mainTest.ml", line 10, characters 4-39:
10 |     SparseMatrixImplementationTest.test () ;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module SparseMatrixImplementationTest
```

We added

```
(select sparseMatrixImplementationTest.ml from
        (apron -> sparseMatrixImplementationTest.apron.ml)
        (-> sparseMatrixImplementationTest.no-apron.ml)
)
```
to `tests/unit/dune` which seems to be ignored in this lower bound test according to the warning. Do you have an idea about that?

2025-02-24 17:41 UTC, sim642 commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
Apparently there was a dune issue regarding the use of alternative dependencies in `test`s specifically: https://github.com/ocaml/dune/issues/9365. This was fixed in dune 3.13.

I now pushed a small dune minimum version fix to your repository. If you run the unlocked CI again, hopefully that fixes the issue.

2025-02-24 20:51 UTC, GollokG commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
Thanks, that fixed the issue!
We also fixed the cyclic dependency issue by adding a dune file to the `tests/unit/cdomains/affineEqualityDomain` subdirectory, as it seems to be handled in similar situations in Goblint.
Is this still the best solution for that problem?

2025-02-25 08:05 UTC, sim642 commented on tests/unit/cdomains/affineEqualityDomain/sparseImplementation/sparseMatrixImplementationTest.ml
> +module D = SharedFunctions.Mpqf
I think so, because that's how it seems to work for Apron stuff in `src/`.
Although now there seems to be two copies of the tests.

2025-02-25 08:07 UTC, sim642 commented
By the way, there are some unresolved comments from @DrMichaelPetter and @michael-schwarz among the long hidden part of this PR.

2025-02-25 08:11 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
I will be adding this myself post merge in a separate PR, since this needs more thinking and testing and is probably out of scope for this course.

2025-02-25 08:12 UTC, DrMichaelPetter commented on src/cdomains/apron/affineEqualityDomain.apron.ml
> +        let col_a, col_b = Matrix.get_col_upper_triangular a s, Matrix.get_col_upper_triangular b s in
This I will also do myself in a coming PR.

2025-02-25 08:15 UTC, DrMichaelPetter commented
> By the way, there are some unresolved comments from @DrMichaelPetter and @michael-schwarz among the long hidden part of this PR. I don't know if there's anything that should still be done w.r.t. those or are they irrelevant by now.

My remarks will be addressed in a future PR to fine-tune performance, @michael-schwarz issues are concerning the array implementation, which I would also address out of the scope of this course submission, in a cleanup-PR.

2025-02-25 13:32 UTC, sim642 approved these changes

2025-02-25 15:26 UTC, DrMichaelPetter requested changes
Ok, one last suggestion: it was probably our fault for not giving you a more precise feedback here: side-effects have a very very different association in the context of the goblint analyzer, and this association is quite dear to us. Let us instead call the property ```sparse``` instead of ```side_effects``` (which entails inverting the condition), and make the bracketed explanations the actual explanations.

Ideally, also the ```AffineEqualityDomainSideEffects``` would rather be the ```AffineEqualityDenseDomain```.

However: With Simmo and me having more or less approved this PR, merging is at the tip of our fingers.

2025-02-25 18:22 UTC, CopperCableIsolator commented
The naming regarding the semantics for "side effects" should now be compliant with the goblint standard. I've tried my best to still convey fully the fact that these functions have an effect on the program state. Also the files have been renamed.

2025-02-25 18:59 UTC, michael-schwarz commented
Thanks! @CopperCableIsolator: I think you accidentally committed some files in the next to last commit?

2025-02-25 19:01 UTC, michael-schwarz commented
Also, I think the conf is not modified yet?

2025-02-26 10:05 UTC, sim642 commented on src/goblint_lib.ml
> +module AffineEqualityDomainDense = AffineEqualityDenseDomain
The docs/api-build CI failure should be fixed by this:
```suggestion
module AffineEqualityDenseDomain = AffineEqualityDenseDomain
```

2025-02-26 11:03 UTC, DrMichaelPetter approved these changes

2025-02-26 12:33 UTC, merged