Introduce a simplified version of td3 with warrowing (see PR 1611)
goblint/analyzer pull request #1626
Opened 2024-11-10 10:04 UTC by FelixKrayer

Copied from PR #1611 by @arkocal 
The simplified warrowing solver

As to which solver we should keep as the simplified version, this one:

1. Can be documented a little more for didactic purposes, but I find it to be very readable as is.
2. We should find the paper most closely matching this solver.
3. This one does not pass all tests due to narrowing.

I created this pullrequest so I can address comments and do changes.
Addressing comments by @sim642 :
1. removed `remove-wpoint` option. Having this option is not necessary for this solver. However, I changed it to always remove wpoints, without checking the config, as this is the default setting in the config.
2. solver data is no longer a record. There is no need for that
3. moved query/side out. There is no real reason they were inside iterate, it was just the way it turned out after deleting  
4. TODO: decide if phases should be included. This solver does not have them, since the parallel solvers do not use them and it was created for comparison with those. However, for generalizing this solver I see the use of implementing the phases.

2024-12-19 10:05 UTC, michael-schwarz commented
@sim642 @arkocal: What is you take on phases or not?
I don't have a strong opinion here, but think we should move forward with merging this.

2024-12-19 10:32 UTC, arkocal commented
I am fine with either variant, so I would have a light preference to just proceed and merge. @sim642 had the point that the basic example should have a termination guarantee, which is reasonable, just not a deal breaker for me as I find warrowing a little more intuitive than phases.

tldr: I would keep it as is, but have no strong preference, so Simmo please feel free to override this if you do.

2024-12-20 09:50 UTC, sim642 requested changes

2024-12-20 09:50 UTC, sim642 commented on src/solver/td_simplified.ml
This module needs to be added to `Goblint_lib` to fix the CI failure.

Also, this PR should be adapted to #1605, i.e., the new solver added to the cram test along with all the others.

2025-01-03 08:55 UTC, sim642 approved these changes

2025-01-03 08:55 UTC, merged